apiVersion: v1
kind: Service
metadata:
  name: app-pagamento
  labels:
    app: app-pagamento
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: port-default
    - port: 8080
      targetPort: 8081
      name: port-fallback
  selector:
    app: app-pagamento
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pagamento
  labels:
    app: app-pagamento
spec:
  selector:
    matchLabels:
      app: app-pagamento
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-pagamento
        tier: frontend
    spec:
      containers:
        - name: app-pagamento
          image: ${{ secrets.ECR_URI }}:app-pagamentos
          imagePullPolicy: Always
          env:
            - name: MYSQL_DATABASE
              value: pagamento_58
            - name: MYSQL_HOST
              value: ${{ secrets.DB_HOST }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: pedidos_service
              value: app-pedido

          ports:
            - containerPort: 8081
              name: app-pagamento
          command: ["/bin/bash", "-c"]
          args:
            - |
              mvn clean package
              mvn spring-boot:run
          resources:
            requests:
              cpu: 700m
      # imagePullSecrets:
      #   - name: regcred

