secretGenerator:
- name: mysql-pass
  literals:
  - password=${{ secrets.DB_PASSWORD }}
resources:
  - app-pedido-deployment.yaml
  - app-pedido-hpa.yaml
  - app-pagamento-deployment.yaml
  - app-pagamento-hpa.yaml
  - webhook-pagamento-deployment.yaml
  - webhook-pagamento-hpa.yaml