apiVersion: v1
kind: Service
metadata:
  name: mysqldb-pagamento
  labels:
    app: mysqldb-pagamento
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysqldb-pagamento
    tier: mysql
  #clusterIP: None
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pagamento-pv-claim
  labels:
    app: mysqldb-pagamento
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-pagamento
  labels:
    app: mysqldb-pagamento
spec:
  selector:
    matchLabels:
      app: mysqldb-pagamento
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqldb-pagamento
        tier: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysqldb
          args:
            - "--lower_case_table_names=1"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_DATABASE
              value: pagamento_58
          ports:
            - containerPort: 3306
              name: mysql-pagamento
          volumeMounts:
            - name: mysql-pagamento-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pagamento-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pagamento-pv-claim
