apiVersion: v1
kind: Service
metadata:
  name: webhook-api
  labels:
    app: webhook-api
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: webhook-api
    tier: mysql
  #clusterIP: None
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-webhook-api-pv-claim
  labels:
    app: webhook-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-api
  labels:
    app: webhook-api
spec:
  selector:
    matchLabels:
      app: webhook-api
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webhook-api
        tier: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: webhook-api
          args:
            - "--lower_case_table_names=1"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_DATABASE
              value: webhook-api
            - name: MYSQL_USER
              value: webhook-api
          ports:
            - containerPort: 3306
              name: webhook-api
          volumeMounts:
            - name: webhook-api-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: webhook-api-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-webhook-api-pv-claim
