apiVersion: v1
kind: Service
metadata:
  name: mysqldb-pedidos
  labels:
    app: mysqldb-pedidos
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysqldb-pedidos
    tier: mysql
  #clusterIP: None
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pedidos-pv-claim
  labels:
    app: mysqldb-pedidos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-pedidos
  labels:
    app: mysqldb-pedidos
spec:
  selector:
    matchLabels:
      app: mysqldb-pedidos
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqldb-pedidos
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysqldb-pedidos
        args:
          - "--lower_case_table_names=1"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: food_58
        ports:
        - containerPort: 3306
          name: mysqldb-pedidos
        volumeMounts:
        - name: mysql-pedidos-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pedidos-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pedidos-pv-claim
