version: "3.8"
services:
  webhook-db:
    container_name: webhook-db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5447:5432"
    environment:
      POSTGRES_USER: webhook-api
      POSTGRES_PASSWORD: /run/secrets/db_pass
      POSTGRES_DB: webhook-api
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api-net
    secrets:
      - db_pass

  webhook-api:
    build: ..
    restart: always
    ports:
      - 5000:5000
    environment:
      FLAG_DEBUG: True
      APP_SECRET_KEY: /run/secrets/app_secret_key
    networks:
      - api-net
    secrets:
      - app_secret_key

networks:
  api-net:
    driver: bridge

secrets:
  db_pass:
    file: db_pass.txt
  app_secret_key:
    file: app_secret_key.txt

volumes:
  postgres_data: {}
