version: "3.8"
services:
  webhook-db:
    container_name: webhook-db
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33061:3306"
      #- "33060:33060"
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: webhook-api
      MYSQL_PASSWORD: /run/secrets/db_pass
      MYSQL_USER: webhook-api
      MYSQL_ROOT_PASSWORD: /run/secrets/db_pass
#      MYSQL_USER: webhook-api
#      MYSQL_PASSWORD: /run/secrets/db_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api-net
    secrets:
      - db_pass
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

  webhook-db-admin:
    image: adminer
    restart: always
    ports:
      - 33090:8080
    networks:
      - api-net

  webhook-api:
    build: ..
    restart: always
    ports:
      - 5000:5000
    environment:
      FLAG_DEBUG: True
      APP_SECRET_KEY: /run/secrets/app_secret_key
      #CREATE_ENGINE_ECHO: True
      DB_USER: webhook-api
      DB_PASSWD: /run/secrets/db_pass
      DB_SCHEMA: webhook-api
      DB_HOST: webhook-db
      DB_PORT: 3306
    networks:
      - api-net
    secrets:
      - app_secret_key
      - db_pass

networks:
  api-net:
    driver: bridge

secrets:
  db_pass:
    file: db_pass.txt
  app_secret_key:
    file: app_secret_key.txt

volumes:
  mysql_data: {}
